<template>
  <div class="spinner">
    <div class="loadingio-spinner-ripple-pzzmvy8oskd">
      <div class="ldio-avvxwjla4sv">
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<style>
@keyframes ldio-avvxwjla4sv {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}
.spinner {
  text-align: center;
}
.ldio-avvxwjla4sv div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-avvxwjla4sv 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.ldio-avvxwjla4sv div:nth-child(1) {
  border-color: #e90c59;
  animation-delay: 0s;
}
.ldio-avvxwjla4sv div:nth-child(2) {
  border-color: #46dff0;
  animation-delay: -0.5s;
}
.loadingio-spinner-ripple-pzzmvy8oskd {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #fef9f8;
}
.ldio-avvxwjla4sv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-avvxwjla4sv div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
